# Server
server.port=8080

# XAMPP MySQL (default user root, no password - change if you use one)
spring.datasource.url=jdbc:mysql://localhost:3306/freshmart_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# File upload - no size limit for images
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1


# Spring Mail (Replace these with your actual SMTP credentials, e.g. Gmail App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=freshmart.direct@gmail.com
spring.mail.password=mvvqlgtaqsmiucni
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
